version: '3'

silent: true

tasks:

  bench:
    desc: Runs benchmarks
    cmds:
      - cmd: cargo +nightly bench

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +stable clippy

  clippy-all:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --all-targets

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-priv:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +nightly test

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt